### ISSUE TITLE
[Docs]: License & Security Policy

### ISSUE THREAD

**Issue by krshkodes** [krshkodes/username-checker#6]
Add the following:

- [License](https://github.com/InnateComm/.github/blob/main/LICENSE) - MIT License
- [Security Policy](https://github.com/InnateComm/.github/blob/main/SECURITY.md) - Informs users on how to report vulnerabilities

**Comment by ykhokhaneshiya** [comment]
@krshkodes , Can I work on this issue?

**Comment by KendallDoesCoding** [comment]
> @krshkodes , Can I work on this issue?

Any update on this? If your not working on it, I would love to work on this.

**Comment by KendallDoesCoding** [comment]
@krshkodes Can I work on this if @ykhokhaneshiya isn't?

**Comment by krshkodes** [comment]
Yes sure @KendallDoesCoding!
