### ISSUE TITLE
[Docs]: Add issues templates & PR template

### ISSUE THREAD

**Issue by krshkodes** [krshkodes/username-checker#7]
Add the following:

- [Issue Templates](https://github.com/InnateComm/.github/tree/main/.github/ISSUE_TEMPLATE) - Basic Issue Templates
- [PR Template](https://github.com/InnateComm/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md) - Fallback PR Template

**Comment by jaynarayan-vaishnav** [comment]
i would like to work on this but need to fully understand what i have to do here? can you pls explain?

**Comment by krshdev** [comment]
Hey there @jaynarayan-vaishnav! You just have to copy the templates from the link mentioned in the issue to this repo!

**Comment by jaynarayan-vaishnav** [comment]
Okay will do that thanks for helping. Pls assign me this issue

**Comment by jaynarayan-vaishnav** [comment]
@krshkodes  i have made a PR so pls review it ☺️
